ALTER TABLE rounds ADD COLUMN IF NOT EXISTS round_type VARCHAR(32);
UPDATE rounds SET round_type = 'BOARD' WHERE round_type IS NULL;
ALTER TABLE rounds ALTER COLUMN round_type SET NOT NULL;

CREATE TABLE IF NOT EXISTS final_round_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL,
    round_id BIGINT NOT NULL,
    player_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    wager INTEGER NOT NULL,
    answer TEXT NOT NULL,
    judged BOOLEAN NOT NULL DEFAULT FALSE,
    correct BOOLEAN,
    CONSTRAINT fk_final_submission_game FOREIGN KEY (game_id) REFERENCES games(id),
    CONSTRAINT fk_final_submission_round FOREIGN KEY (round_id) REFERENCES rounds(id),
    CONSTRAINT fk_final_submission_player FOREIGN KEY (player_id) REFERENCES players(id),
    CONSTRAINT fk_final_submission_question FOREIGN KEY (question_id) REFERENCES questions(id),
    CONSTRAINT uk_final_submission_player UNIQUE (game_id, round_id, player_id)
);
