CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    display_order INTEGER,
    pack_id BIGINT
);

ALTER TABLE categories
    ADD COLUMN IF NOT EXISTS display_order INTEGER;

ALTER TABLE categories
    ADD COLUMN IF NOT EXISTS pack_id BIGINT;

ALTER TABLE questions
    ADD COLUMN IF NOT EXISTS display_order INTEGER;

ALTER TABLE questions
    ADD COLUMN IF NOT EXISTS category_id BIGINT;

INSERT INTO packs (name, description)
SELECT 'Starter Pack', 'First pack for local development'
WHERE NOT EXISTS (
    SELECT 1 FROM packs WHERE name = 'Starter Pack'
);

INSERT INTO categories (name, display_order, pack_id)
SELECT 'Geography', 1, (SELECT id FROM packs WHERE name = 'Starter Pack')
WHERE NOT EXISTS (
    SELECT 1 FROM categories WHERE name = 'Geography'
);

INSERT INTO questions (text, answer, price, display_order)
SELECT 'Capital of France?', 'Paris', 100, 1
WHERE NOT EXISTS (
    SELECT 1 FROM questions WHERE text = 'Capital of France?'
);

UPDATE categories
SET display_order = COALESCE(display_order, 1),
    pack_id = COALESCE(pack_id, (SELECT id FROM packs WHERE name = 'Starter Pack'))
WHERE name = 'Geography';

UPDATE questions
SET pack_id = COALESCE(pack_id, (SELECT id FROM packs WHERE name = 'Starter Pack')),
    category_id = COALESCE(category_id, (SELECT id FROM categories WHERE name = 'Geography')),
    display_order = COALESCE(display_order, 1)
WHERE text = 'Capital of France?';
