CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

-- Add user_id column to players if it does not exist (Postgres-safe)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'players' AND column_name = 'user_id'
    ) THEN
        ALTER TABLE players ADD COLUMN user_id BIGINT;
    END IF;
END$$;

-- Add foreign key constraint if it does not exist
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'fk_players_user' AND table_name = 'players'
    ) THEN
        ALTER TABLE players
            ADD CONSTRAINT fk_players_user FOREIGN KEY (user_id) REFERENCES users(id);
    END IF;
END$$;
