CREATE TABLE IF NOT EXISTS rounds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    display_order INTEGER,
    pack_id BIGINT
);

ALTER TABLE categories
    ADD COLUMN IF NOT EXISTS round_id BIGINT;

ALTER TABLE questions
    ADD COLUMN IF NOT EXISTS round_id BIGINT;

ALTER TABLE games
    ADD COLUMN IF NOT EXISTS current_round_id BIGINT;

INSERT INTO rounds (name, display_order, pack_id)
SELECT 'Round 1', 1, p.id
FROM packs p
WHERE NOT EXISTS (
    SELECT 1 FROM rounds r WHERE r.pack_id = p.id
);

UPDATE categories c
SET round_id = r.id
FROM rounds r
WHERE c.pack_id = r.pack_id
  AND r.display_order = 1
  AND c.round_id IS NULL;

UPDATE questions q
SET round_id = r.id
FROM rounds r
WHERE q.pack_id = r.pack_id
  AND r.display_order = 1
  AND q.round_id IS NULL;

UPDATE games g
SET current_round_id = r.id
FROM rounds r
WHERE g.pack_id = r.pack_id
  AND r.display_order = 1
  AND g.current_round_id IS NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_name = 'rounds' AND constraint_name = 'fk_rounds_pack'
    ) THEN
        ALTER TABLE rounds
            ADD CONSTRAINT fk_rounds_pack FOREIGN KEY (pack_id) REFERENCES packs(id) ON DELETE CASCADE;
    END IF;
END$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_name = 'categories' AND constraint_name = 'fk_categories_round'
    ) THEN
        ALTER TABLE categories
            ADD CONSTRAINT fk_categories_round FOREIGN KEY (round_id) REFERENCES rounds(id) ON DELETE SET NULL;
    END IF;
END$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_name = 'questions' AND constraint_name = 'fk_questions_round'
    ) THEN
        ALTER TABLE questions
            ADD CONSTRAINT fk_questions_round FOREIGN KEY (round_id) REFERENCES rounds(id) ON DELETE SET NULL;
    END IF;
END$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_name = 'games' AND constraint_name = 'fk_games_current_round'
    ) THEN
        ALTER TABLE games
            ADD CONSTRAINT fk_games_current_round FOREIGN KEY (current_round_id) REFERENCES rounds(id);
    END IF;
END$$;
